spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: amila
      password: amila
      host: localhost
      port: 27017
      authentication-database: admin
server:
  port: 8090