spring:
  data:
    mongodb:
      username: amila
      password: amila
      host: localhost
      port: 27017
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.amila.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.amila.ecommerce.notification.PaymentNotificationRequest
  application:
    name: notification-service
  mail:
    host: localhost
    port: 1025
    username: amila
    password: amila
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040